### ISSUE TITLE
batch process

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/RevilMax#1]
hi predator,

i'd like to know if there is a good way to do batch process with your max plugin?
basically i want to go through all motion in .85 file one by one, and i met issue with current build

i can use "importFile" command to load anim, but cannot assign which anim take should be loaded by command, tried change index number in ini file but seems no effect

any idea?
thanks!

**Comment by PredatorCZ** [comment]
.ini file is only for UI stuff, a dialog must be opened to load ini values.
I presume, you're using #noPrompt, in this case .ini values won't work.
There is no way to set motlist index, only thru UI.

However, I have plans for motlist to mot packer/unpacker.
In that case you can load one mot file per scene. Export it. Clear scene. Repeat. AFAIK those commands exists.

**Comment by redtankbai** [comment]
ok, will wait your motlist unpacker to keep going, thx

**Comment by redtankbai** [comment]
hi predator,
i know you have other stuff need to do, but just let you know that im still waiting this feature and it will help me a lot
thx!

**Comment by PredatorCZ** [comment]
You can try build dev branch, but no promises. Last commit was a few weeks ago, maybe months.

**Comment by redtankbai** [comment]
i have no cook enviroment, so cannot get dev branch work ...
but i have an idea to make batch work with a funny way

a saparate question, how could i get motion take name after anim imported? i can see the name in list of UI, but not in listener output, any public verialble have that?

**Comment by PredatorCZ** [comment]
They do not, all is internal, you can try to copy (Ctrl-C) value directly from listbox, no guaranties, that it will work.

**Comment by redtankbai** [comment]
could you make it can be read by script?

**Comment by redtankbai** [comment]
well, i got everything done by myself, in an ugly way, but batch working with anim name now, thx for the inform!
