### ISSUE TITLE
Monster Hunter Rise (Switch Demo version)

### ISSUE THREAD

**Issue by Demonslayerx8** [PredatorCZ/RevilMax#12]
Monster Hunter Rise uses Revil engine, and formats are .mesh, .tex, and .mdf2, but sadly meshes fail to import, however bones import fine.

Currently all the files extracted are hashed due to being in a single pak file with no file list available yet. Here's a few [mesh and texture samples](https://mega.nz/folder/QhM30YyT#5liOOmDmAC_lsFBbZXh73Q).

![image](https://user-images.githubusercontent.com/17195757/104000101-9e4dd080-5152-11eb-8f20-19e1490a6706.png)
![image](https://user-images.githubusercontent.com/17195757/104001372-68a9e700-5154-11eb-9c57-5e7302086897.png)

**Comment by PredatorCZ** [comment]
M8, are you sure you have the correct project?
There is a literary About section, where you can contact original author.
