### ISSUE TITLE
L_WeaponHand、R_WeaponHand positions turn to "nan" 

### ISSUE THREAD

**Issue by kenshin20080-lab** [PredatorCZ/RevilMax#14]
I imported "pl0300_yamato.motlist.85" into 3DS Max with "load all" checked,  then I export all the animations to a fbx.

But when I import this fbx into Blender 2.90, I found L_WeaponHand's position values turned to "nan" since frame 228.

And I noticed that if I import "pl0300_yamato.motlist.85" into 3DS Max with "select Animation", this problem wont happen.

Can you help me? Thank you for your great job

**Comment by kenshin20080-lab** [comment]
This is "pl0300_yamato.motlist.85" :
https://mega.nz/#!N00hDCAZ!4IbbqXiUbrQ_SfR4ykgaSFuF6TsF9RIWzuH3jfw5smY

**Comment by PredatorCZ** [comment]
Does the same happen, when you reimport fbx?

**Comment by kenshin20080-lab** [comment]
Yes, it happened even if I reimport the fbx.

**Comment by kenshin20080-lab** [comment]
This problem also happened when I import Provoke_10 in "pl0200_special.motlist.85" (which is V's umbrella dance motion). R_WeaponHand's position turned to "nan" since frame 882.

**Comment by kenshin20080-lab** [comment]
I noticed that it was OK in 3ds max, but, if I export animations to a fbx, then import that fbx into other 3d softwares( Blender, Motionbuilder), some of bones' transitions may lost for some reason...

**Comment by kenshin20080-lab** [comment]
Problem solved (manually, not perfect).
I found this problem is caused by some broken keyframes (maybe devide by zero or something).
So all we have to do is removing those broken keyframes manually after motlist import.
I think it's better to fix this in revilmax plugin instead of manual proccess.

**Comment by PredatorCZ** [comment]
From the first glance, it looks like a controller issue.
When I change rotation controller to `Euler XYZ` and back to `Linear Rotation`, the defect disappears.

**Comment by PredatorCZ** [comment]
It looks like controllers don't like unnormalized quaternions.

**Comment by kenshin20080-lab** [comment]
Yes,that worked! Thank you so much

**Comment by PredatorCZ** [comment]
Issue should be fixed in v1.7

**Comment by kenshin20080-lab** [comment]
Thank you
