### ISSUE TITLE
Bones get hidden

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [PredatorCZ/RevilMax#18]
I have recorded a video [here](https://youtu.be/3XHiAeDgukk) to show the issue.

At a certain frame, the bones get hidden, and subsequently, there are problems with the fbx.

The motlist "pl0000_base_cmn_damg.motlist.99" is attached.
[pl0000_base_cmn_damg.motlist.99.zip](https://github.com/PredatorCZ/RevilMax/files/6527144/pl0000_base_cmn_damg.motlist.99.zip)

**Comment by PredatorCZ** [comment]
Looks like the issue from #14 persisted. Do you use latest version (v1.7+)?

**Comment by NoteToSelfFindGoodNickname** [comment]
Yes, I did use the latest version.
I have also tried v1.8 now, and I think the problem is still the same.

Here is a screenshot of frame 15216 in the motlist "pl0000_base_cmn_damg.motlist.99"
Tested with Max 2017.

![gone1](https://user-images.githubusercontent.com/29504639/119271071-39c27800-bc00-11eb-8e63-1ae9ade98139.jpg)

**Comment by PredatorCZ** [comment]
try v1.8.1

**Comment by NoteToSelfFindGoodNickname** [comment]
Thank you, that seems to work.
