### ISSUE TITLE
some motlist.484 has empty name

### ISSUE THREAD

**Issue by qiankanglai** [PredatorCZ/RevilMax#24]
Hi PredatorCZ,

Thanks for this great work. I follow [the instruction](https://residentevilmodding.boards.net/thread/14132/motlist-maxscript-custom-animations-engine) here trying to extract some MHRise animation, but the plugin crashes for some motlist.484.

> But it is the same format as RE8's animations internally. I've built a version of Revilmax for 3dsmax 2017 that can import MHRise motlists, but it will not work for RE8 anymore.

From this, I modified the source code a bit to debug (duplicate `motion_list_486` and `motion_458` and rename) and found it crashes due to empty name.

![image](https://user-images.githubusercontent.com/1546130/153324030-fbee46cf-9112-40c0-bd55-443d35ed0388.png)

I add some protection code to avoid this and it works, but any idea for better extracting? It seems some motlist does have `NULL` name 😢

**Comment by PredatorCZ** [comment]
Some names might be missing on purpose for some reason. There is no way to get them, since they were omitted at build.

**Comment by qiankanglai** [comment]
Got it. Thank you.
