### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by DarkNemesisUmbrella** [PredatorCZ/RevilMax#4]
Hey man! can you do a tutorial of how to use this plugin ? I really need it but i dont know how to get 3d models from RE2 Remake and the animations and how to use this plugin

**Comment by PredatorCZ** [comment]
Check Xentax community, I believe there is a Noesis script for importing models.
You aren't explicitly using this plugin, it just provide an interface for importing. All you need to do is just import the file. Also you don't need to import a model at all to load an animation.

**Comment by DarkNemesisUmbrella** [comment]
But where is that interface of this plugin ? I tried importing a FBX 3d model and nothing shows me

**Comment by DarkNemesisUmbrella** [comment]
Anyway. I already know how to use this plugin, sorry for bother xD for anyone who may ask, you just need to import any file and it will let you import the animations files.
THANKS YOU FOR YOUR AWESOME TOOL! this really help me a lot.

**Comment by PredatorCZ** [comment]
No problem, I'm closing this now.
