### ISSUE TITLE
.motlist.99 anim crash 3DMax when import

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/RevilMax#7]
here is an example
https://drive.google.com/open?id=17QwhHdW-ulSmzVt7iDVKMRcLhJZGlqBh

there are about 40% .motlist.99 has this kind of issue
plz let me know if you need more example

thanks!

**Comment by PredatorCZ** [comment]
Issues might have been fixed in V1.3.

**Comment by redtankbai** [comment]
it's working, many thx!
