### ISSUE TITLE
motlist about DMC5

### ISSUE THREAD

**Issue by AnimatorBullet** [PredatorCZ/RevilMax#8]
Hi，PredatorCZ

I uploaded a file that will cause crash when I import it to 3ds max 2014，I use the RevilMax with 1.3.7.Please help me!

Looking for your response.
Thank you

**Comment by PredatorCZ** [comment]
Issue should be fixed in V1.4.

**Comment by AnimatorBullet** [comment]
> Issue should be fixed in V1.4.

Thanks！
