### ISSUE TITLE
v1.3 crashes 3dmax on import

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/RevilMax#9]
keep doing import action for same motion file, and will get crash at 2nd or 3rd import
can survive longer if import different motion file, got best score is 5 import action but crash at 6th

same thing happens on .85 and .99 files
both max 2014 and 2016 has this issue

reset max before import not help

**Comment by PredatorCZ** [comment]
Issue should be fixed in V1.4.

**Comment by redtankbai** [comment]
fixed, thanks!
